### ISSUE TITLE
请问：LogHub ETL 的UDF 能否调用外部服务？ 

### ISSUE THREAD

**Issue by swituo** [aliyun/aliyun-log-fc-functions#1]
比如要转换IP->地址，需要调用外部服务得到结果，服务也是部在阿里云上的。这个可以么？

谢谢。

**Comment by wind1719** [comment]
可以的。函数内只要网络能通，就是可以访问外部资源，是可以DIY的。

目前有两个限制：

1. 网络可以访问ecs经典网络（内网）、公网

2. 暂时不支持vpc（后续会支持，请关注函数计算团队公告）

**Comment by swituo** [comment]
@wind-tangkai 

非常感谢。

再麻烦问个问题，如果location以提供的例子转换，ipdata能得到后续更新么？（可以是购买阿里云的产品或服务的方式）

**Comment by wind1719** [comment]
@swituo 建议用 http://ip.taobao.com/instructions.php，这里可以用api方式访问。
也可以去这里下载免费的ipdata，看起来会定期更新的，https://www.ipip.net/index.html#down

**Comment by swituo** [comment]
thanks !
